version: "2.0"

networks:
  v_network:

services:
  node:
    image: node
    user: "root"
    networks:
      - v_network
    working_dir: /home/node/app
    restart: always
    volumes:
      - /media/Datos/Proyectos/kasita.es-react/backend:/home/node/app
    ports:
      - 3001:3001
    command: "npm start"
    environment:
      - PORT=3001
      - USER=jma
      - PASSWORD=311000oo
      - SECRET="losgatitossonmonos"
