version: "2.0"

networks:
  v_network:

services:
  mongo:
    image: bitnami/mongodb
    restart: always
    networks:
      - v_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 666696969

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - v_network
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 666696969

  node:
    image: node
    user: "root"
    networks:
      - v_network
    depends_on:
      - mongo
    links:
      - "mongo:db"
    working_dir: /home/node/app
    restart: always
    volumes:
      - /mnt/Datos/Nextcloud/Proyectos/kasita/backend:/home/node/app
    ports:
      - 3001:3001
    command: "npm start"
    environment:
      - PORT=3001
